AWSTemplateFormatVersion: "2010-09-09"
Description: Glue Crawler for Enriched Zone Data


Resources:

  # ==========================================
  # GLUE DATABASE (Athena database)
  # ==========================================
  EnrichDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: enrich
        Description: Enriched analytics layer


  # ==========================================
  # GLUE CRAWLER (runs on enriched S3 path)
  # ==========================================
  EnrichCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: enrich-transformed-crawler

      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/glue-execution-role

      DatabaseName: enrich

      Targets:
        S3Targets:
          - Path: s3://enriched-zone-00/transformed/data/

      TablePrefix: enrich_

      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG

      RecrawlPolicy:
        RecrawlBehavior: CRAWL_NEW_FOLDERS_ONLY


Outputs:
  DatabaseName:
    Value: enrich

  CrawlerName:
    Value: enrich-transformed-crawler
