AWSTemplateFormatVersion: "2010-09-09"
Description: Simple EC2 instance

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  MyEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      ImageId: ami-0f5ee92e2d63afc18
