AWSTemplateFormatVersion: "2010-09-09"
Description: AWS Glue Job 

Parameters:
  GlueJobName:
    Type: String
    Default: glueETL

  ScriptS3Path:
    Type: String
    Default: s3://bronze-10/script/gluejob.py

  TempDir:
    Type: String
    Default: s3://bronze-10/temp/
    
  BronzeInputPath:
    Type: String
    Description: Default raw input path
    Default: s3://group10-entire-dataset/unzip_csv/

  SilverOutputPath:
    Type: String
    Description: Default transformed output path
    Default: s3://silver-10/transformed/
    
  WorkerType:
    Type: String
    Default: G.1X
    AllowedValues:
      - G.1X
      - G.2X

  NumberOfWorkers:
    Type: Number
    Default: 3

    
Resources:

  # -------------------------------------------------
  # IAM ROLE FOR GLUE
  # -------------------------------------------------
  GlueExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: glue-execution-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole

      Policies:
        - PolicyName: GlueS3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::bronze-10
                  - arn:aws:s3:::bronze-10/*
                  - arn:aws:s3:::group10-entire-dataset
                  - arn:aws:s3:::group10-entire-dataset/*
                  - arn:aws:s3:::silver-10
                  - arn:aws:s3:::silver-10/*

  # -------------------------------------------------
  # GLUE JOB
  # -------------------------------------------------
  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Ref GlueJobName
      Role: !GetAtt GlueExecutionRole.Arn
      GlueVersion: "4.0"
      WorkerType: G.1X
      NumberOfWorkers: 3

      Command:
        Name: glueetl
        PythonVersion: "3"
        ScriptLocation: !Ref ScriptS3Path

      DefaultArguments:
        "--job-language": "python"
        "--enable-metrics": ""
        "--enable-continuous-cloudwatch-log": "true"
        "--enable-glue-datacatalog": ""
        "--TempDir": !Ref TempDir
        "--BRONZE_INPUT_PATH": !Ref BronzeInputPath
        "--SILVER_OUTPUT_PATH": !Ref SilverOutputPath

      ExecutionProperty:
        MaxConcurrentRuns: 1

Outputs:
  GlueJobName:
    Description: Created Glue Job Name
    Value: !Ref GlueJobName
