AWSTemplateFormatVersion: "2010-09-09"
Description: AWS Glue Job 

Parameters:
  GlueJobName:
    Type: String
    Default: glueETL

  ScriptS3Path:
    Type: String
    Default: s3://glue-etl-script-00/script/gluejob.py

  TempDir:
    Type: String
    Default: s3://glue-etl-script-00/temp/
    
  InputPath:
    Type: String
    Description: Default raw input path
    Default: s3://group10-entire-dataset/unzip_csv/OP_DTL_GNRL_PGYR2024_P06302025_06162025.csv

  OutputPath:
    Type: String
    Description: Default transformed output path
    Default: s3://enriched-zone-00/transformed_1/
    
  WorkerType:
    Type: String
    Default: G.1X
    AllowedValues:
      - G.1X
      - G.2X

  NumberOfWorkers:
    Type: Number
    Default: 10

    
Resources:

  # -------------------------------------------------
  # IAM ROLE FOR GLUE
  # -------------------------------------------------
  GlueExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: glue-execution-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole

      Policies:
        - PolicyName: GlueS3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::glue-etl-script-00
                  - arn:aws:s3:::glue-etl-script-00/*
                  - arn:aws:s3:::raw-zone-00
                  - arn:aws:s3:::raw-zone-00/*
                  - arn:aws:s3:::enriched-zone-00
                  - arn:aws:s3:::enriched-zone-00/*

  # -------------------------------------------------
  # GLUE JOB
  # -------------------------------------------------
  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Ref GlueJobName
      Role: !GetAtt GlueExecutionRole.Arn
      GlueVersion: "4.0"
      WorkerType: !Ref WorkerType
      NumberOfWorkers: !Ref NumberOfWorkers

      Command:
        Name: glueetl
        PythonVersion: "3"
        ScriptLocation: !Ref ScriptS3Path

      DefaultArguments:
        "--job-language": "python"
        "--enable-metrics": ""
        "--enable-continuous-cloudwatch-log": "true"
        "--enable-glue-datacatalog": ""
        "--TempDir": !Ref TempDir
        "--INPUT_PATH": !Ref InputPath
        "--OUTPUT_PATH": !Ref OutputPath

      ExecutionProperty:
        MaxConcurrentRuns: 5

Outputs:
  GlueJobName:
    Description: Created Glue Job Name
    Value: !Ref GlueJobName
