AWSTemplateFormatVersion: '2010-09-09'
Description: CMS Website Ingestion Glue Job


# ==================================================
# PARAMETERS (MANDATORY because you use !Ref)
# ==================================================
Parameters:

  GlueJobName:
    Type: String
    Default: cms-website-ingestion

  WorkerType:
    Type: String
    Default: G.1X

  NumberOfWorkers:
    Type: Number
    Default: 5


# ==================================================
# RESOURCES
# ==================================================
Resources:

  GlueRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess


  GlueIngestionJob:
    Type: AWS::Glue::Job
    Properties:

      Name: !Ref GlueJobName
      Role: !GetAtt GlueRole.Arn

      # ✅ MUST be glueetl for Spark
      Command:
        Name: glueetl
        ScriptLocation: s3://glue-etl-script-0/script/data_ingest.py
        PythonVersion: 3

      GlueVersion: "4.0"

      # ✅ Spark compute settings (NOT MaxCapacity)
      WorkerType: !Ref WorkerType
      NumberOfWorkers: !Ref NumberOfWorkers

      DefaultArguments:
        "--RAW_BUCKET": "raw-zone-0"
        "--URL": "https://download.cms.gov/openpayments/PGYR2024_P01232026_01102026/OP_DTL_GNRL_PGYR2024_P01232026_01102026.csv"
        "--job-language": "python"


# ==================================================
# OUTPUT
# ==================================================
Outputs:

  JobName:
    Value: !Ref GlueIngestionJob
