AWSTemplateFormatVersion: '2010-09-09'
Description: cms-website-ingestion

Resources:

  GlueRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess


  GlueIngestionJob:
    Type: AWS::Glue::Job
    Properties:
      Name: cms-website-ingestion
      Role: !GetAtt GlueRole.Arn

      Command:
        Name: glueetl
        ScriptLocation: !Ref ScriptS3Path
        PythonVersion: 3


      GlueVersion: "4.0"
      MaxCapacity: 5

      DefaultArguments:
        "--RAW_BUCKET": "raw-zone-00"
        "--URL": "https://download.cms.gov/openpayments/PGYR2024_P01232026_01102026/OP_DTL_GNRL_PGYR2024_P01232026_01102026.csv"
        "--job-language": python
