AWSTemplateFormatVersion: '2010-09-09'
Description: Data lake S3 buckets

Resources:

  ScriptBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: script-bucket
      VersioningConfiguration:
        Status: Disabled

  RawZoneBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: raw-zone
      VersioningConfiguration:
        Status: Disabled

  EnrichBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: enrich-bucket
      VersioningConfiguration:
        Status: Disabled

  ReportingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: reporting-zone
      VersioningConfiguration:
        Status: Disabled
