name: Glue-ETL-Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - script/gluejob.py
      - Lambda-iceberg-table/athena_trigger.py
      - CFT/lambda.yml

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      # ==========================================
      # AWS AUTH
      # ==========================================
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      # ==========================================
      # UPLOAD Data-Ingestion SCRIPT
      # ==========================================
      - name: Upload ingestion script to S3
        run: |
          aws s3 cp script/data_ingest.py s3://glue-etl-script-00/script/data_ingest.py

      # ---------------------------------
      # Deploy for Data-Ingestion Glue Job
      # ---------------------------------
      - name: Deploy CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file CFT/ingestion_job.yml \
            --stack-name data-ingestion \
            --capabilities CAPABILITY_NAMED_IAM
      # ==========================================
      # START INGESTION GLUE JOB
      # ==========================================
      - name: Start Ingestion Glue Job
        id: start_ingest
        run: |
          INGEST_RUN_ID=$(aws glue start-job-run \
            --job-name data-ingestion \
            --region us-east-1 \
            --query 'JobRunId' \
            --output text)

          echo "INGEST_RUN_ID=$INGEST_RUN_ID" >> $GITHUB_ENV


      # ==========================================
      # WAIT FOR INGESTION JOB FINISH
      # ==========================================
      - name: Wait for ingestion completion
        run: |
          while true; do
            STATUS=$(aws glue get-job-run \
              --job-name data-ingestion \
              --run-id $INGEST_RUN_ID \
              --region us-east-1 \
              --query 'JobRun.JobRunState' \
              --output text)

            echo "Ingestion status: $STATUS"

            if [ "$STATUS" = "SUCCEEDED" ]; then
              break
            fi

            if [ "$STATUS" = "FAILED" ] || [ "$STATUS" = "STOPPED" ]; then
              exit 1
            fi

            sleep 32
          done

      # ==========================================
      # UPLOAD SCRIPT
      # ==========================================
      - name: Upload ETL script to S3
        run: |
          aws s3 cp script/gluejob.py s3://glue-etl-script-00/script/gluejob.py

      # ==========================================
      # DEPLOY GLUE JOB FOR TRANSFORMATION
      # ==========================================
      - name: Deploy Glue Job via CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file CFT/glue_job.yml \
            --stack-name glue-creation \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              GlueJobName=glueETL \
              ScriptS3Path=s3://glue-etl-script-00/script/gluejob.py \
              WorkerType=G.1X \
              NumberOfWorkers=5 \
              InputPath=s3://raw-zone-00/direct/ \
              OutputPath=s3://enriched-zone-00/transformed_1/ \
            --region us-east-1


      # ==========================================
      # START GLUE JOB + CAPTURE RUN ID
      # ==========================================
      - name: Start AWS Glue Job
        id: startjob
        run: |
          JOB_RUN_ID=$(aws glue start-job-run \
            --job-name glueETL \
            --region us-east-1 \
            --query 'JobRunId' \
            --output text)

          echo "JOB_RUN_ID=$JOB_RUN_ID" >> $GITHUB_ENV


      # ==========================================
      # WAIT FOR JOB FINISH 
      # ==========================================
      - name: Wait for Glue job completion
        run: |
          while true; do
            STATUS=$(aws glue get-job-run \
              --job-name glueETL \
              --run-id $JOB_RUN_ID \
              --region us-east-1 \
              --query 'JobRun.JobRunState' \
              --output text)

            echo "Glue status: $STATUS"

            if [ "$STATUS" = "SUCCEEDED" ]; then
              break
            fi

            if [ "$STATUS" = "FAILED" ] || [ "$STATUS" = "STOPPED" ]; then
              exit 1
            fi

            sleep 30
          done
          
    # ==========================================
      # ZIP LAMBDA
      # IMPORTANT: python file must be at root
      # ==========================================
      - name: Package Lambda
        run: zip -j athena_trigger.zip Lambda-iceberg-table/athena_trigger.py



      # ==========================================
      # UPLOAD ZIP TO S3
      # ==========================================
      - name: Upload Lambda package to S3
        run: aws s3 cp athena_trigger.zip s3://glue-etl-script-00/athena_trigger.zip

      # ==========================================
      # DEPLOY CLOUDFORMATION (Lambda stack)
      # ==========================================
      - name: Deploy Lambda Stack
        run: |
          aws cloudformation deploy \
            --template-file CFT/lambda.yml \
            --stack-name lambda-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --region ${{ secrets.AWS_REGION }}
      
