name: Glue-ETL-Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - script/gluejob.py

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload ETL script to S3
        run: |
          aws s3 cp script/gluejob.py s3://bronze-10/script/gluejob.py
      - name: Start AWS Glue Job
        run: |
          aws glue start-job-run \
          --job-name gluejob \
          --arguments '{
            "--SCRIPT_S3_PATH":"s3://bronze-10/script/gluejob.py",
            "--RAW_INPUT_PATH":"s3://group10-entire-dataset/unzip_csv/",
            "--OUTPUT_PATH":"s3://silver-10/transformed/"
          }'
