name: Glue-ETL-Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - script/gluejob.py

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      # ==========================================
      # AWS AUTH
      # ==========================================
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      # ==========================================
      # UPLOAD SCRIPT
      # ==========================================
      - name: Upload ingestion script to S3
        run: |
          aws s3 cp script/data_ingest.py s3://glue-etl-script-00/script/data_ingest.py

      # ---------------------------------
      # Deploy for data-ingestion Glue Job
      # ---------------------------------
      - name: Deploy CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file data_ingest.yaml \
            --stack-name glue-ingestion-stack \
            --capabilities CAPABILITY_NAMED_IAM

      # ==========================================
      # UPLOAD SCRIPT
      # ==========================================
      - name: Upload ETL script to S3
        run: |
          aws s3 cp script/gluejob.py s3://glue-etl-script-00/script/gluejob.py

      # ==========================================
      # DEPLOY GLUE JOB
      # ==========================================
      - name: Deploy Glue Job via CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file CFT/glue_job.yml \
            --stack-name glue-creation \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              GlueJobName=glueETL \
              ScriptS3Path=s3://glue-etl-script-00/script/gluejob.py \
              WorkerType=G.1X \
              NumberOfWorkers=5 \
              InputPath=s3://raw-zone-00/data/OP_DTL_GNRL_PGYR2024_P06302025_06162025.csv \
              OutputPath=s3://enriched-zone-00/transformed/data/ \
            --region us-east-1


      # ==========================================
      # START GLUE JOB + CAPTURE RUN ID
      # ==========================================
      - name: Start AWS Glue Job
        id: startjob
        run: |
          JOB_RUN_ID=$(aws glue start-job-run \
            --job-name glueETL \
            --region us-east-1 \
            --query 'JobRunId' \
            --output text)

          echo "JOB_RUN_ID=$JOB_RUN_ID" >> $GITHUB_ENV


      # ==========================================
      # WAIT FOR JOB FINISH (IMPORTANT)
      # ==========================================
      - name: Wait for Glue job completion
        run: |
          while true; do
            STATUS=$(aws glue get-job-run \
              --job-name glueETL \
              --run-id $JOB_RUN_ID \
              --region us-east-1 \
              --query 'JobRun.JobRunState' \
              --output text)

            echo "Glue status: $STATUS"

            if [ "$STATUS" = "SUCCEEDED" ]; then
              break
            fi

            if [ "$STATUS" = "FAILED" ] || [ "$STATUS" = "STOPPED" ]; then
              exit 1
            fi

            sleep 30
          done


      # ==========================================
      # DEPLOY CRAWLER STACK
      # ==========================================
      - name: Deploy Crawler Stack
        run: |
          aws cloudformation deploy \
            --template-file CFT/crawler_job.yml \
            --stack-name my-crawler \
            --capabilities CAPABILITY_NAMED_IAM


      # ==========================================
      # START CRAWLER
      # ==========================================
      - name: Start Crawler
        run: |
          aws glue start-crawler \
            --name enrich-transformed-crawler
